### PR TITLE
fixes #4455 fix(nimbus): submitErrors casing fix in stories + Branches

### LINKED ISSUE #4455: snakeToCamelCase in CommonForm hook causing submit errors not to be displayed in Storybook
I _think_ this is just affected in Storybook, but this PR: https://github.com/mozilla/experimenter/pull/4363/commits

Looks like this in Storybook: https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/763dba338f9bd679780a700bca1eb2ea151f2674/nimbus-ui/index.html?path=/story/components-formaudience--server-submit-errors

Before this commit, the errors were displayed: https://storage.googleapis.com/mozilla-storybooks-experimenter/commits/2c6ea4a0c67bb5e48852d301fd8fec0d5bb2f74a/nimbus-ui/index.html?path=/story/components-formaudience--server-submit-errors

This is also the case in our other forms.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-855)
┆Issue Number: EXP-855

### PR DESCRIPTION
**Pull request by LZoog**
Because:
* Many submit errors were not being displayed in at least Storybook

This commit:
* Removes case conversion in Branches now that its handled in useCommonForm (at least 'feature_value' submitError was not showing)
* Fixes some stories that had camelCase submit errors

fixes #4455 

---

@lmorchard even with proper snake_case `submitErrors` in Branches, the `feature_value` error wasn't showing. Doesn't look like we need `normalizeFieldNames` anymore since we're doing a case conversion in `useCommonForm`.

### CODE REVIEW

File: app/experimenter/nimbus-ui/src/components/FormBranches/reducer/actions.ts [hunk 1]
```diff
@@ -215,21 +213,6 @@ function setSubmitErrors(
   };
 }
 
-// Server-side field names are in snake-case, client-side field names are
```
Comment (lmorchard) [inline app/experimenter/nimbus-ui/src/components/FormBranches/reducer/actions.ts:218]: Oh! Hmm, yeah I think I forgot this needed excising in the earlier PR

**Review by lmorchard — APPROVED** [review]
LGTM, conflicts from the merge of PR #4438 notwithstanding
