### PR TITLE
bug(nimbus): Support latest uniffi changes in application services

### LINKED ISSUE #10521: Cannot update to latest application-services nightlies
A-S has updated uniffi and the generated python code now uses relative imports (fml.py imports `.remotesettings`). However, there is no __init__.py to make the megazord a real module, so the imports itself don't work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4457)

### PR DESCRIPTION
**Pull request by brennie**
Because

- application-services updated uniffi, which resulted in generating
  Python with relative imports;

This commit:

- updates our application-services packaging to produce a
  `nimbus_megazord` Python package; and
- updates to the latest application-services build.

Fixes #10521

### CODE REVIEW

File: application-services/fetch-application-services.sh [hunk 1]
```diff
@@ -35,6 +35,10 @@ function prepare_megazord {
     fi
 
     mkdir -p "megazords/${PROJECT}"
+
+    # Create a __init__.py so that the generated megazord behaves like a
+    # package and allows for relative imports.
+    touch "megazords/${PROJECT}/__init__.py"
```
Comment (yashikakhurana) [inline application-services/fetch-application-services.sh:41]: 🎉

**Review by yashikakhurana — APPROVED** [review]
Thank you @brennie for fixing that :shipit:
