### PR TITLE
bug(nimbus): fix outcome slug lookup to filter by app

### LINKED ISSUE #9505: Validate that outcomes are for the correct application
There was a [recent experiment](https://experimenter.services.mozilla.com/nimbus/ios-felt-privacy/summary) on Firefox for iOS that appears to be using a Fenix outcome. I'm not sure if this is accurate or just a UI issue, but we should investigate and confirm that experiments can't be configured with outcomes that don't match the application of the experiment.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3889)

### PR DESCRIPTION
**Pull request by mikewilli**
Because

- there can be overlaps in outcome slugs across applications
- we saw some experiment summary pages linking to the wrong application's outcome definitions

This commit

- ensures that the outcomes hook filters to the experiment's application

Fixes #9505

### CODE REVIEW

File: experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx [hunk 1]
```diff
@@ -18,8 +18,19 @@ export function useOutcomes(experiment: getExperiment_experimentBySlug): {
       return [];
     }
 
+    if (experiment.application === null) {
+      return slugs
+        .map((slug) => outcomes!.find((outcome) => outcome!.slug === slug))
+        .filter((outcome) => outcome != null);
+    }
```
Comment (jaredlockhart) [inline experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx:25]: Application can never be null, is this here because typescript forces you to deal with the null case?

Comment (brennie) [reply experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx:25]: its because the graphql is incorrect

Comment (brennie) [reply experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx:25]: https://github.com/mozilla/experimenter/blob/a518f6feda664a67c1e2a97a12a59713f371187c/experimenter/experimenter/experiments/api/v5/types.py#L335

this should be `graphene.NonNull(graphene.List(graphene.NonNull(NimbusOutcomeType))` (or something similar)

Comment (brennie) [reply experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx:25]: Oops I relized i commented about outcome, not application. Thats https://github.com/mozilla/experimenter/blob/a518f6feda664a67c1e2a97a12a59713f371187c/experimenter/experimenter/experiments/api/v5/types.py#L136 and it should be `graphene.NonNull(...)`

Comment (mikewilli) [reply experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx]: Updated these and regenerated types.

File: experimenter/experimenter/nimbus-ui/src/lib/mocks.tsx [hunk 2]
```diff
@@ -1141,8 +1141,19 @@ export function mockOutcomeSets(experiment: getExperiment_experimentBySlug): {
       return [];
     }
 
+    if (experiment.application === null) {
+      return slugs
+        .map((slug) => outcomes!.find((outcome) => outcome!.slug === slug))
+        .filter((outcome) => outcome != null);
+    }
```
Comment (jaredlockhart) [inline experimenter/experimenter/nimbus-ui/src/lib/mocks.tsx:1148]: So you should be able to get rid of this case right?

File: experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx (hunk 1 above)
Comment (jaredlockhart) [reply experimenter/experimenter/nimbus-ui/src/hooks/useOutcomes.tsx]: Oh yeah I wasn't gonna say we should change all the types, probably just a `!` would've been sufficient.

File: experimenter/experimenter/nimbus-ui/src/lib/mocks.tsx (hunk 2 above)
Comment (mikewilli) [reply experimenter/experimenter/nimbus-ui/src/lib/mocks.tsx]: Yep, good catch! I forgot that this function was copied into the tests.

**Review by jaredlockhart — APPROVED** [review]
Much nicer, thnx @mikewilli 🙏
