### PR TITLE
fixes #4459 fix(nimbus): Address UI DOM/test console warnings

### LINKED ISSUE #4459: Flaky console error in DirectoryTable test
Low priority unless this starts creeping up in CI, but I noticed yesterday at least twice when running `nimbus-ui` tests that this console error would pop up.

Seems like `slug: `some-experiment-${Math.round(Math.random() * 100)}` sometimes ends up producing the same number. Didn't poke at the code but it's probably more ideal to use something like a uuid here, or maybe just increasing the number is good enough.

```
    console.error ../../node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Encountered two children with the same key, `some-experiment-21`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
          in tbody (at DirectoryTable/index.tsx:120)
          in table (at DirectoryTable/index.tsx:94)
          in div (at DirectoryTable/index.tsx:93)
          in DirectoryTable (at DirectoryTable/index.tsx:190)
          in DirectoryCompleteTable (at PageHome/index.tsx:47)
          in div (at PageHome/index.tsx:46)
          in div (created by TabPane)
          in Transition (created by Fade)
          in Fade (created by TabPane)
          in TabPane (created by Tabs)
          in div (created by ForwardRef)
          in ForwardRef (created by Tabs)
          in TabContainer (created by Tabs)
          in Tabs (at PageHome/index.tsx:38)
          in Body (at PageHome/index.tsx:77)
          in div (at AppLayout/index.tsx:16)
          in main (created by Container)
          in Container (at AppLayout/index.tsx:15)
          in AppLayout (at PageHome/index.tsx:61)
          in PageHome (at PageHome/index.test.tsx:48)
          in ApolloProvider (at mocks.tsx:214)
          in MockedCache (at PageHome/index.test.tsx:47)
          in Subject (at PageHome/index.test.tsx:55)
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-858)
┆Issue Number: EXP-858

### PR DESCRIPTION
**Pull request by LZoog**
fixes #4459 

Because:
* A test was occasionally logging a warning about duplicate experiment keys

This commit:
* Fixes the flaky console error in DirectoryTable test by accepting the mapped array's index in the callback
* Fixes a 'whitespace text' DOM warning noticed when running tests by explicitly returning null in a ternary
* Moves an inline style into a class for reuse later

### CODE REVIEW

File: app/experimenter/nimbus-ui/src/lib/mocks.tsx [hunk 1]
```diff
@@ -421,9 +421,10 @@ fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);
 /** Creates a single mock experiment suitable for getAllExperiments queries.  */
 export function mockSingleDirectoryExperiment(
   overrides: Partial<getAllExperiments_experiments> = {},
+  slugIndex: number = Math.round(Math.random() * 100),
 ): getAllExperiments_experiments {
   return {
-    slug: `some-experiment-${Math.round(Math.random() * 100)}`,
+    slug: `some-experiment-${slugIndex}`,
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/lib/mocks.tsx:427]: This is what fixes the issue because we call this function [here](https://github.com/mozilla/experimenter/blob/2497b9c205c76d14360ba90fde59b31e3d50f11d/app/experimenter/nimbus-ui/src/lib/mocks.tsx#L492) and it receives each object `override` + index.

File: app/experimenter/nimbus-ui/src/components/Summary/TableAudience/index.tsx [hunk 2]
```diff
@@ -72,17 +67,17 @@ const TableAudience = ({ experiment }: TableAudienceProps) => {
...
+          <tr>
+            <th>Full targeting expression</th>
+            <td
+              data-testid="experiment-target-expression"
+              className="text-monospace"
+            >
+              <Code codeString={experiment.jexlTargetingExpression} />
+            </td>
+          </tr>
+        ) : null}
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/components/Summary/TableAudience/index.tsx:80]: This one's the extra console warning fixed:

image

I'm actually not entirely sure why it apparently outputs an empty string/text node - I thought it was perhaps the indentation, but I turned off autoformat on save to play around with it without much success so our options seemed to be 1) remove the `experiment.jexlTargetingExpression` check and add a `!` to `codeString={experiment.jexlTargetingExpression}` to suppress TS complaints (👎 since this can be `null`) 2) explicitly render `null` in a ternary or 3) keep digging.

File: app/experimenter/nimbus-ui/src/components/Summary/TableAudience/index.tsx [hunk 3]
```diff
@@ -20,12 +20,7 @@ const TableAudience = ({ experiment }: TableAudienceProps) => {
   const { firefoxMinVersion, channel, targetingConfigSlug } = useConfig();
 
   return (
-    <Table
-      bordered
-      data-testid="table-audience"
-      className="mb-4"
-      style={{ tableLayout: "fixed" }}
-    >
+    <Table bordered data-testid="table-audience" className="mb-4 table-fixed">
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/Summary/TableAudience/index.tsx:23]: Bless u

**Review by jodyheavener — APPROVED** [review]
LGTM! Weeeeird dom warning

**Comment by jaredlockhart** [comment]
Oh good thanks for clearing these up @LZoog !
