### PR TITLE
Fix #4696: fix(visualization) - Null checks where appropriate.

### LINKED ISSUE #4696: Can't access property "friendly_name"
Sentry: [https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/10693845](https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/10693845/?referrer=slack)

See it happening in this experiment: [https://experimenter.services.mozilla.com/nimbus/chrome-attribution-beta-84-diagnostic/results](https://experimenter.services.mozilla.com/nimbus/chrome-attribution-beta-84-diagnostic/results)

The issue is occurring because `metricsMetaData[metric]!` is nulll, on this line: [https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLocked/index.tsx#L67:L67](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutSidebarLocked/index.tsx#L67:L67)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1009)
┆Issue Number: EXP-1009

### PR DESCRIPTION
**Pull request by emtwo**
Because:
* Some pages don't load when there is no weekly data or metadata

This commit:
* Removes assumptions about the availability of weekly and meta data to fix page load issues

### CODE REVIEW

**Review by jaredlockhart — APPROVED** [review]
Thnx for fast turnaround @emtwo ! I guess we'll resolve those sentry errors and see if they come back 👍

File: app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx [hunk 1]
```diff
@@ -247,7 +247,7 @@ const TableVisualizationRow: React.FC<{
   }
 
   return tableLabel === TABLE_LABEL.HIGHLIGHTS ? (
-    <div key={metricKey} className={`${className} py-2`}>
+    <div key={metricKey} className={`${className} py-2`} data-tip={tooltipText}>
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx:250]: Ohh was this missing from previous PR?

**Review by LZoog — APPROVED** [review]
LGTM, seems like the right fix

File: app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx (hunk 1 above)
Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx:250]: yes it was, I noticed it when the page actually loaded

Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx]: Actually, I checked a different experiment and realized this was doing a double tooltip. So removed this change. I'll file a separate issue because the tooltips dont show up in the case when retention is not computed

File: app/experimenter/nimbus-ui/src/components/PageResults/TableMetricSecondary/index.tsx [hunk 2]
```diff
@@ -132,10 +132,12 @@ const TableMetricSecondary = ({
           })}
         </tbody>
       </table>
-      <GraphsWeekly
-        weeklyResults={results?.weekly!}
-        {...{ probeSetSlug, probeSetName }}
-      />
+      {results?.weekly && (
+        <GraphsWeekly
+          weeklyResults={results?.weekly}
```
Comment (pdehaan) [inline app/experimenter/nimbus-ui/src/components/PageResults/TableMetricSecondary/index.tsx:137]: Not sure if this still needs a "?" in the `results?.weekly` since we're already doing that check above on L135 now. But not sure it hurts anything either, unless TypeScript is terrible at its job.

Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/PageResults/TableMetricSecondary/index.tsx:137]: good point, I'll remove it

**Comment by pdehaan** [comment]
Ah! This might be why I'm currently seeing a General Application Error on https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/multi-stage-aboutwelcome-set-default-as-first-screen-v2/results

**Comment by emtwo** [comment]
> Ah! This might be why I'm currently seeing a General Application Error on https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/multi-stage-aboutwelcome-set-default-as-first-screen-v2/results

Yes! This fix should hopefully address that :)

**Comment by pdehaan** [comment]
> Yes! This fix should hopefully address that :)

Confirmed _General Application Error_ is fixed.
