### PR TITLE
fix #7532 feat(nimbus): Use previous state to update issticky require…

### LINKED ISSUE #7532: Sticky Enrollment checkbox appears unchecked after navigating from the Metrics page using the Save and Continue button
**[Prerequisites]:**

* Have an experiment in the DRAFT state on the Nimbus Stage server with the `Sticky Enrollment` option checked.

**[Steps to reproduce]:**

1. Navigate to the `Metrics` section of the experiment page from prerequisites.
1. Press the `Save and Continue` button.
1. Observe the Sticky Enrollment checkbox.

**[Expected result]:**

* The option is still checked.

**[Actual result]:**

* The option becomes unchecked after a few seconds.

**[Notes]:**

* The sticky enrollment option is still `true` on the Details page.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2619)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/26721">sticky enrollment unchecked in UI, but still checked on the details page.gif</a>

### PR DESCRIPTION
**Pull request by yashika-khurana**
Because

* Sticky enrollment state was using false as a default value, which leads to these issues
#7532 
#7533 
#7534

This commit

* Uses the experimenter is sticky value as a default state 

fixes #7532 #7533 #7534

### CODE REVIEW

File: app/experimenter/nimbus-ui/src/components/PageEditAudience/FormAudience/index.tsx [hunk 1]
```diff
@@ -82,7 +82,9 @@ export const FormAudience = ({
     experiment!.languages.map((v) => "" + v.id!),
   );
 
-  const [isSticky, setIsSticky] = useState<boolean>(false);
+  const [isSticky, setIsSticky] = useState<boolean>(
+    experiment.isSticky ?? false,
+  );
```
Comment (jaredlockhart) [inline app/experimenter/nimbus-ui/src/components/PageEditAudience/FormAudience/index.tsx:87]: Oh right yeah, we missed this on the first pr 😅 Anyways looks good but can you pls also add a couple tests to verify the cases where it's set on the model or not 🙏

**Review by jaredlockhart — CHANGES_REQUESTED** [review]

**Review by jaredlockhart — APPROVED** [review]
Fantastic thank you @yashika-khurana 😸
