### PR TITLE
fixes #4661 feat(nimbus): make request review page always accessible 

### LINKED ISSUE #4661: Re-enable and display review blockers on Request Review page
The Request Review page is currently disabled until the server has determined that the experiment can be put into review. In an effort to more clearly point out missing fields and have all “Save and Continue” buttons enabled let’s display these front and center if you try to go to review.

1. Re-enable the Request Review page.

* Remove the PageRequestReview redirect found [here.](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx#L118:L122)
* Merge the [Review & Launch LinkNav and DisabledItem](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppLayoutWithSidebar/index.tsx#L103:L138) into a single LinkNav while keeping the “Missing Details In” bit.

1. Re-enable the Save and Continue button on the Audience page.
1. In the [PageRequestReview](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx#L114:L114) hide the Request Review container and display a container that shows the pages that are missing detail. Use [this](https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=218758%3A0) design.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-985)
┆Issue Number: EXP-985

### LINKED ISSUE #4806: Can't access review page, but no missing fields warnings?
This might be an edge case / obsolete with the upcoming changes to making review always accessible, but I thought I should file just in case:

**Actual:** Review view is greyed out after filling in all my fields:

!image-2021-03-12-08-27-55-582.png!

**Expected**:  I should either see what's missing or be able to access Review and Launch

See this staging experiment to reproduce:

[https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/asdasdasd_asdasdasdasd/edit/branches](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/asdasdasd_asdasdasdasd/edit/branches)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1068)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15454/image-2021-03-12-08-27-53-098.png">image-2021-03-12-08-27-53-098.png</a> | <a href="https://jira.mozilla.com/secure/attachment/15453/image-2021-03-12-08-27-55-582.png">image-2021-03-12-08-27-55-582.png</a>
┆Issue Number: EXP-1068

### PR DESCRIPTION
**Pull request by jodyheavener**
Closes #4661
Closes #4806

Opening now for early looks. I'm going to add some more tests but this should generally be good to look at.

This PR:

- Make the Review & Launch page always accessible
- When required fields are missing they will still display in the sidebar, but they will also display on the Review & Launch page, blocking any launch UI

### CODE REVIEW

**Comment by LZoog** [comment]
Haven't looked at this quite yet but I think it will close https://github.com/mozilla/experimenter/issues/4806 too?

**Comment by jodyheavener** [comment]
@LZoog Ah yup, I have it linked in Jira but I will add it here as well 👍

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx [hunk 1]
```diff
@@ -30,12 +30,31 @@ type PageRequestReviewProps = {
...
+        // Return to the experiment root/summary page
+        return "";
+      }
+    }}
+  >
+    {({ experiment, refetch }) => <PageContent {...{ experiment, refetch }} />}
+  </AppLayoutWithExperiment>
+);
+
+const PageContent: React.FC<{
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx:49]: I did this so we could stop using using refs to pass the experiment around in this component. Open to suggestions if this is too clunky. I wish we were using Context to pass experiment data around.

Comment (lmorchard) [reply app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx:49]: Yeah, I've kind of got it in the back of my head & todo list to take a swing at moving this experiment lookup into Context. A couple wrinkles there that *could* be worked out maybe

That said, IMO this PageContent subcomponent is fine. It at least gets us out of a few levels of indentation

Comment (LZoog) [reply app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx:49]: @jodyheavener did you already have a WIP branch of using `Context` from a few months back or am I misremembering something? Would be out of date now but that sounds vaguely familiar.

Comment (jodyheavener) [reply app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx:49]: @LZoog @lmorchard yeah! I have [this](https://github.com/mozilla/experimenter/compare/jh/context?expand=1) (now very outdated) branch from a few months back where I moved experiment and analysis data to Context. Doesn't do much for LoC but it made things so much simpler IMO. One side effect I saw was that we could largely stop mocking the experiment GQL query in tests/Storybook and instead just mock the context value. It was too large to PR all at once so I was hoping to one day start incrementally moving towards it.

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx [hunk 2]
```diff
@@ -77,145 +96,125 @@ const PageRequestReview = ({
...
+          {submitError}
+        </Alert>
+      )}
 
-            {(status.draft || status.preview) && (
-              <ChangeApprovalOperations
+      {(status.draft || status.preview) && invalidPages.length > 0 ? (
+        <Alert variant="warning">
+          Before this experiment can be reviewed or launched, all required
+          fields must be completed. Fields on <InvalidPagesList /> are missing
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/components/PageRequestReview/index.tsx:118]: Definitely not blocking, but I feel like the phrasing here could be better? "Fields on **the** [pages] **page(s)** are missing details."

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.stories.tsx [hunk 3]
```diff
@@ -39,6 +39,19 @@ export default {
   decorators: [withLinks],
 };
 
+export const missingRequiredFields = storyWithExperimentProps(
+  {
+    readyForReview: {
+      ready: false,
+      message: {
+        reference_branch: ["This field may not be null."],
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/components/PageRequestReview/index.stories.tsx:47]: Doesn't affect your PR (thinking outloud here) and I know we're using the same error messages from the server now I wonder if we have a ticket for reviewing any of these error messages, or do you know how we landed on them? I feel like using the word `null` isn't really user friendly. For the risk mitigation questions, I think something like, "This question must be answered." feels a little better...

image

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.test.tsx [hunk 4]
```diff
@@ -74,45 +74,18 @@ describe("PageRequestReview", () => {
...
-    render(<Subject mocks={[mock]} />);
-    await waitFor(() => {
-      expect(
-        navigate,
-      ).toHaveBeenCalledWith(
-        `${BASE_PATH}/${experiment.slug}/edit/overview?show-errors`,
-        { replace: true },
-      );
-    });
+    await screen.findByText(/all required fields must be completed/);
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/components/PageRequestReview/index.test.tsx:87]: Could potentially be nice to have a test to make sure "Fields on X" renders properly, like a test for a single page (without a comma) and then a list of them with commas.

**Review by LZoog — COMMENTED** [review]
I'm having trouble getting Storybook to work (not on this branch specifically, on another this morning as well) and am not sure why, so I'm going to reinstall all the things and potentially restart my machine and circle back, but figured I'd leave you these comments first and then circle back to likely r+ after another looksee. PR looks great. 👏

**Review by LZoog — APPROVED** [review]
OK, got Storybook running and went through the flow in Experimenter to poke around make sure a review could still be requested etc., and it all LGTM. Just have the one test suggestion and non-blocking couple of questions. 😎

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.stories.tsx (hunk 3 above)
Comment (jodyheavener) [reply app/experimenter/nimbus-ui/src/components/PageRequestReview/index.stories.tsx:47]: Yup, I agree, and to an extent this is initially why I was using client-side messages. I believe these messages are automatically generated from the [serializer](https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/api/v5/serializers.py#L533:L533). Not entirely sure what the process is for overriding each one. Could've sworn there was an issue for this but I don't see it so here's a new one: https://jira.mozilla.com/browse/EXP-1315

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.test.tsx (hunk 4 above)
Comment (jodyheavener) [reply app/experimenter/nimbus-ui/src/components/PageRequestReview/index.test.tsx:87]: Good point, but since Fields on X is a component returned by the hook I updated to test in the [hook](https://github.com/mozilla/experimenter/pull/5236/files#diff-e2aa547f541309725ea10252e740cae5aacaab33f89b4d04b9c8114913858a31R105) instead of this component (since it's used in multiple spots)

File: app/experimenter/nimbus-ui/src/components/PageRequestReview/index.stories.tsx (hunk 3 above)
Comment (jaredlockhart) [reply app/experimenter/nimbus-ui/src/components/PageRequestReview/index.stories.tsx:47]: Yeah you can just set this as a parameter to the fields in the serializer, so we can address it on the backend and if the frontend just uses the server messages it'll just pick them up 👍
