### PR TITLE
fixes #4164: fix(visualization) show loader until data loads.

### LINKED ISSUE #4164: Visualization page loads summary table first
This is a bug. The summary table is shown briefly until the visualizations have loaded.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-689)
┆Issue Number: EXP-689

### PR DESCRIPTION
**Pull request by emtwo**
Because
* We don't want content flashing then changing

This commit
* Waits for data to load before showing content

### CODE REVIEW

File: app/experimenter/nimbus-ui/src/components/AppLayoutWithExperiment/index.tsx [hunk 1]
```diff
@@ -88,7 +81,7 @@ const AppLayoutWithExperiment = ({
     };
   }, [startPolling, stopPolling, experiment, polling]);
 
-  if (experimentLoading || analysisRequired) {
```
Comment (emtwo) [inline app/experimenter/nimbus-ui/src/components/AppLayoutWithExperiment/index.tsx:91]: The issue, I noticed, was that `experimentLoading` would become false but `analysisRequired` would also become false due to the `useEffect()` that I removed. There, the experiment would be done loading but `analysisLoading` would still be false because it would not have started loading yet. Then `analysisRequired` is set to false too soon, causing the summary table to display first.

I found that `analysisRequired` didn't seem necessary since we can just check `analysisLoading` instead.

**Comment by emtwo** [comment]
@jodyheavener I think you made some of these changes in `AppLayoutWithExperiment` so I wanted to check with you what you think of this?

**Comment by emtwo** [comment]
For reference, here's a link where the bug happens: https://experimenter.services.mozilla.com/nimbus/attribution-targeting-release-aa-test/results

**Comment by jodyheavener** [comment]
Darn I thought I had solved that. @emtwo since this component is used on every Experiment page, can you confirm that this change still only performs the analysis request on pages that require it? For example, none of the Edit pages should need to wait for analysis request to complete.

**Comment by emtwo** [comment]
> Darn I thought I had solved that. @emtwo since this component is used on every Experiment page, can you confirm that this change still only performs the analysis request on pages that require it? For example, none of the Edit pages should need to wait for analysis request to complete.

Oh! That makes sense why you were checking `analysisRequired` then. It was whether it's required for the current page. I think this change doesn't address this.

Back to the drawing board!

**Comment by jodyheavener** [comment]
Hmmm. `AppLayoutWithExperiment` is getting pretty bloated as it is. I wonder if we should split that component into two components; one targeted at Design/Results pages (which should always perform the analysis request) and one targeted at the Edit/Request Review pages (which should never perform that request)? cc @LZoog

**Comment by emtwo** [comment]
What if we use the same component but pass in an optional prop `analysisRequired`. It would be false by default. But `PageResults` would set it to true. I don't think that's *too* much additional bloating

**Comment by jodyheavener** [comment]
Oh hey that seems like a very reasonable solution 🤦

**Comment by jodyheavener** [comment]
Note that `PageDesign` also needs it, since the sidebar that is displayed with that page needs to know if the analysis is ready or not.

**Comment by emtwo** [comment]
@jodyheavener I updated it with what I mentioned. Works now without loading analysis for edit pages

File: app/experimenter/nimbus-ui/src/components/PageDesign/index.tsx [hunk 2]
```diff
@@ -8,7 +8,11 @@ import AppLayoutWithExperiment from "../AppLayoutWithExperiment";
 
 const PageDesign: React.FunctionComponent<RouteComponentProps> = () => {
   return (
-    <AppLayoutWithExperiment title="Design" testId="PageDesign">
+    <AppLayoutWithExperiment
+      title="Design"
+      testId="PageDesign"
+      analysisRequired={true}
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/PageDesign/index.tsx:14]: Minor, not a blocker: I think you can just specify the prop (not need to set `={true}`)

File: app/experimenter/nimbus-ui/src/components/AppLayoutWithExperiment/index.tsx [hunk 3]
```diff
@@ -56,7 +58,6 @@ const AppLayoutWithExperiment = ({
   // is complete and we inspect its status. To prevent content from flashing on the screen
   // between the experiment and analysis requests, assume we need to wait for analysis
   // until we can prove otherwise.
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/AppLayoutWithExperiment/index.tsx:60]: This comment should be able to be removed (or reworded) since it's not longer relevant.

File: app/experimenter/nimbus-ui/src/components/AppLayoutWithExperiment/index.tsx [hunk 4]
```diff
@@ -88,7 +83,7 @@ const AppLayoutWithExperiment = ({
     };
   }, [startPolling, stopPolling, experiment, polling]);
 
-  if (experimentLoading || analysisRequired) {
+  if (experimentLoading || (analysisRequired && analysisLoading)) {
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/AppLayoutWithExperiment/index.tsx:86]: Hmmmm, I think you will still get a flash of content here. `experimentLoading` becomes false ever so slightly before `analysisLoading` becomes true. You can see this locally by throttling the Network tab to something like 3G, but I assume this would be more visible once deployed. 

It's almost like we need a way for `analysisLoading` to _start_ true. Or we need a way to do `(experimentLoading || (analysisRequired && analysisRequestComplete))` to check if the request was finished (which would be irrelevent in renders where analysisRequired is false). 🤔

**Review by jodyheavener — COMMENTED** [review]
@emtwo I love how simple this change is, but I'm unsure if it solves the problem you're encountering (see last comment). Happy to discuss more!

**Comment by jodyheavener** [comment]
One thing to consider with what I just pushed: I think this would show an indefinite loading screen if there is a legit error performing the analysis request.

**Review by jodyheavener — APPROVED** [review]
I'm biased but I think this looks _GREAT_

**Comment by emtwo** [comment]
@LZoog adding you here since Jody and I both made changes and we need an unbiased opinion

**Review by LZoog — APPROVED** [review]
LGTM!
