### PR TITLE
fixes #8498 fix(nimbus): change search bar so that it checks if input…

### LINKED ISSUE #8498: Search space issue
We added a search box on the landing page,
image
 but if you will write just `pdf` and `pdf ` with space, the results are different, so we want that whenever we search for something, we should add a space after that here- https://github.com/mozilla/experimenter/blob/86c4d1d7e8c9ab20d1a5d07568cb542655238266/experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx#LL94 , so before calling search to modify search term and add space after that

### PR DESCRIPTION
**Pull request by Prithvi-Chanchal**
… contains space at the end or not, if it does not have space at end add space at end and also change test case according to that

Because

- getting different result when input string in search bar is with space and without space

This commit

- change the search bar such that it checks if input string contains space at the end or not, if input string does not contain any space at the end add space at end
- modify the test cases according to the change

### CODE REVIEW

**Comment by Prithvi-Chanchal** [comment]
@yashika-khurana I have modified the test file in page home also, please check that and see if it will cause error anywhere'

File: experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx [hunk 1]
```diff
@@ -58,6 +58,16 @@ const SearchBar: React.FunctionComponent<SearchBarProps> = ({
...
+    // Check if the input value already has a space at the end
+    if (
+      inputValue.length > 0 &&
+      inputValue.charAt(inputValue.length - 1) !== " "
+    ) {
+      // If not, add a space at the end
+      inputValue = inputValue + " ";
+    }
+
     setSearchTerms(event.target.value);
```
Comment (yashikakhurana) [inline experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx:71]: you can do `setSearchTerms(inputValue)`

File: experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx [hunk 2]
```diff
@@ -66,7 +76,7 @@ const SearchBar: React.FunctionComponent<SearchBarProps> = ({
       setClearIcon(true);
 
       const newTimer = setTimeout(() => {
-        const results = fuse.search(searchTerms);
+        const results = fuse.search(inputValue);
```
Comment (yashikakhurana) [inline experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx:79]: then you don't have to do this

**Review by yashikakhurana — CHANGES_REQUESTED** [review]
thank you @Prithvi-Chanchal, one suggestion to use that state itself, let me know if you have any questions thank you :)

File: experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx (hunk 2 above)
Comment (Prithvi-Chanchal) [reply experimenter/experimenter/nimbus-ui/src/components/PageHome/SearchBar/index.tsx:79]: Yes I have already tried that, but the when you type anything it will add space after every character and show that in search bar and you could not delete anything in the search bar, you can only add new characters but they will also be added with space.
see this screen shot for reference:
Screenshot from 2023-03-25 00-20-59
if we enter 'lol' it will be take input as 'l o l ' like this that's why I am not modifying setSeachTerms.
@yashikakhurana

**Comment by Prithvi-Chanchal** [comment]
@yashikakhurana ma'am could you please check, if I have done it right

**Review by yashikakhurana — APPROVED** [review]
thank you @Prithvi-Chanchal looks good now, thank you for updating the test cases too :)
