### PR TITLE
Removing branches no longer clears all data - Fixes #1882

### LINKED ISSUE #1882: Removing a branch deletes all values from remaining branch
Steps to reproduce

1) Create three branches
2) Fill them all in with invalid data
3) Submit to server, get errors
4) Delete the middle branch
5) The last branch has all its fields emptied out

branch-fields

### PR DESCRIPTION
**Pull request by rehandalal**
This also involves a large refactor of the components code to help prevent errors like this from happening down the line.

r?

### CODE REVIEW

File: app/experimenter/static/js/components/AddonForm.js [hunk 1]
```diff
@@ -2,67 +2,86 @@ import React from "react";
...
+                Enter the URL where the release build of your add-on can be
+                found. This is often attached to a bugzilla ticket. This MUST BE
+                the release signed add-on (not the test add-on) that you want
+                deployed.
+                <a
+                  target="_blank"
+                  rel="noreferrer noopener"
+                  href="https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Add-ons"
+                >
+                  {" "}
```
Comment (rehandalal) [inline app/experimenter/static/js/components/AddonForm.js]: oh, i just noticed this. i'll fix this as it should not be here.

File: app/experimenter/static/js/components/PrefForm.js [hunk 2]
```diff
@@ -3,99 +3,120 @@ import { Row, Col } from "react-bootstrap";
...
+          as="select"
+          helpContent={
+            <div>
+              <p>
+                Select the pref branch the experiment will write its pref value
+                to. If you're not sure what this means, you should stick to the
+                'default' pref branch. Pref branches are a little more
+                complicated than can be written here, but you can find
+                <a href="https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Code_snippets/Preferences#Default_preferences">
+                  {" "}
```
Comment (rehandalal) [inline app/experimenter/static/js/components/PrefForm.js]: same here.
