### PR TITLE
fixes #4165: fix(visualization) Add retention tooltip.

### LINKED ISSUE #4165: When retention is not displayed due to a short duration, this should be shown on hover
┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-688)
┆Issue Number: EXP-688

### PR DESCRIPTION
**Pull request by emtwo**
Because
* We want users to understand why retention is missing

This commit
* Adds a tooltip for when retention is missing

### CODE REVIEW

**Comment by emtwo** [comment]
Screen Shot 2020-12-14 at 11 24 52 AM

File: app/experimenter/nimbus-ui/src/components/TableVisualizationRow/index.tsx [hunk 1]
```diff
@@ -168,9 +171,11 @@ const TableVisualizationRow: React.FC<{
   const metricData = branch_data[metricKey];
 
   let field = <>{metricName} is not available</>;
+  let tooltipText =
+    metricKey === METRIC.RETENTION ? GENERAL_TIPS.MISSING_RETENTION : "";
   let className = "text-danger";
   if (metricData) {
-    className = "";
+    className = tooltipText = "";
```
Comment (jaredlockhart) [inline app/experimenter/nimbus-ui/src/components/TableVisualizationRow/index.tsx:178]: Does the little `= ""` need to be at the end still?

File: app/experimenter/nimbus-ui/src/lib/visualization/constants.ts [hunk 2]
```diff
@@ -30,6 +30,11 @@ export const BADGE_TIPS = {
   GUARDRAIL_METRIC: "Metric that should not regress",
 };
 
+export const GENERAL_TIPS = {
+  MISSING_RETENTION:
+    "Retention is only available after at least 1 week of data post enrollment",
```
Comment (jaredlockhart) [inline app/experimenter/nimbus-ui/src/lib/visualization/constants.ts:35]: 👍 👍 👍 👍

**Review by jaredlockhart — APPROVED** [review]
No test for this?  Not sure if it needs one, could have one though if you want.  Looks good!

File: app/experimenter/nimbus-ui/src/components/TableVisualizationRow/index.tsx (hunk 1 above)
Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/TableVisualizationRow/index.tsx:178]: yes. we need to reset it

Comment (pdehaan) [reply app/experimenter/nimbus-ui/src/components/TableVisualizationRow/index.tsx:178]: Yeah, it's a double assignment where we're setting *both* `className` and `tooltipText` to an empty string.
I think ESLint has a rule for disallowing multi-assignments and forces you to do two separate `className = ""; tooltipText = "";` assignments instead.
