### PR TITLE
fixes #8204 fix(nimbus): added condition to not render 'Audience' lin…

### LINKED ISSUE #8204: Completed rollouts have an “Audience” link in the sidebar
**[Prerequisites]:**

* Have a completed rollout (e.g. this [+stage rollout+](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/edit/summary)).

**[Steps to reproduce]:**

1. Open the rollout from prerequisites and observe the sidebar.
1. Click the “Audience” link from the sidebar.

**[Expected result]:**

* Completed rollouts do not have an “Audience” link in the sidebar.

**[Actual result]:**

* Completed rollouts have an “Audience” link in the sidebar.

**[Notes]:**

* Fields on the Audience page that gets accessed can be edited, but the changes can not be saved.
* Attached is a screen recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3100)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33396">audience.gif</a>

### PR DESCRIPTION
**Pull request by Avi-88**
…k if a Rollout has status 'COMPLETE'

Because

- previously the rollouts that are completed also had a link to the "Audience" page which shouldn't be the case.

Before:

image

This commit

- change the conditional rendering for the "Audience" page link so that completed rollouts do not have it rendered.

After:

image

### CODE REVIEW

File: experimenter/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx [hunk 1]
```diff
@@ -193,6 +193,7 @@ export const AppLayoutSidebarLaunched = ({
               />
 
               {experiment.isRollout &&
+                experiment.status !== "COMPLETE" &&
```
Comment (yashikakhurana) [inline experimenter/experimenter/nimbus-ui/src/components/AppLayoutSidebarLaunched/index.tsx:196]: 🎉

**Review by yashikakhurana — APPROVED** [review]
thank you @Avi-88, great job and test case is on point 💯 👏
