### PR TITLE
Fix #4927: fix(visualization): broken weekly table headers.

### LINKED ISSUE #4927: Missing Weekly Table Headings
There seems to be a bug clearly seen here:
https://experimenter.services.mozilla.com/nimbus/reminder-set-firefox-as-default/results

There seem to be perhaps two problems:
1. The headings are missing
2. I'm not sure that there should be that many columns

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1141)
┆Issue Number: EXP-1141

### PR DESCRIPTION
**Pull request by emtwo**
Because:
* Segmented experiments were resulting broken weekly tables
* Missing weekly analysis were not correctly reflected in table headers

This commit:
* Only looks at "all" segment for experiments (for now)
* Makes sure headers are accurate even when data is missing

### CODE REVIEW

**Comment by emtwo** [comment]
Bug can be found here: https://experimenter.services.mozilla.com/nimbus/reminder-set-firefox-as-default/results

Screenshot below with the fix applied:

File: app/experimenter/nimbus-ui/src/lib/visualization/mocks.tsx [hunk 1]
```diff
@@ -149,6 +149,79 @@ export const WEEKLY_CONTROL = {
   },
 };
 
+export const WONKY_WEEKLY_TREATMENT = {
```
Comment (jaredlockhart) [inline app/experimenter/nimbus-ui/src/lib/visualization/mocks.tsx:152]: giphy

File: app/experimenter/visualization/api/v3/models.py [hunk 2]
```diff
@@ -38,6 +42,7 @@ class JetstreamDataPoint(BaseModel):
     statistic: str = None
     window_index: str = None
     comparison: str = None
+    segment: str = Segment.ALL
```
Comment (jaredlockhart) [inline app/experimenter/visualization/api/v3/models.py:45]: I love to see it 👏 👏 👏

File: app/experimenter/visualization/api/v3/models.py [hunk 3]
```diff
@@ -132,9 +137,13 @@ def __init__(self, result_metrics, data, experiment, window="overall"):
         super(ResultsObjectModelBase, self).__init__()
 
         for jetstream_data_point in data:
+            if jetstream_data_point.segment != Segment.ALL:
+                continue
```
Comment (jaredlockhart) [inline app/experimenter/visualization/api/v3/models.py:141]: Fantastic 👏 👏 👏 👏

File: app/experimenter/nimbus-ui/src/components/PageResults/TableWeekly/index.tsx [hunk 4]
```diff
@@ -25,7 +25,7 @@ const getWeekCount = (
   metric: string,
   weeklyResults: { [branch: string]: BranchDescription },
 ) => {
-  let maxWeeks = 0;
+  const weekIndexSet = new Set();
```
Comment (jaredlockhart) [inline app/experimenter/nimbus-ui/src/components/PageResults/TableWeekly/index.tsx:28]: Sets are the best 👍 👍 👍

**Review by jaredlockhart — APPROVED** [review]
Big 👍 from me
