### PR TITLE
fix(nimbus): fix indefinite page loading on new results page

### LINKED ISSUE #14625: The Results page is in constant Loading state after a different Reference branch was selected and the Back button was pressed
**[Prerequisites]:**

* Have the new Nimbus Results page from an experiment (e.g.: [+https://experimenter.services.mozilla.com/nimbus/desktop-release-relay-holdback/results-new/?analysis_basis=enrollments&reference_branch=disabled&segment=+](https://experimenter.services.mozilla.com/nimbus/desktop-release-relay-holdback/results-new/?analysis_basis=enrollments&reference_branch=disabled&segment=))

**[Steps to reproduce]:**

1. Change the Reference branch to a different one than the default.

1. Click the Back button to undo the changes.

1. Observe the behavior.

**[Expected result]:**

* The Results page is loading for a short time and the old branch is now set as the Reference branch,

**[Actual result]:**

* The page is in constant loading for several minutes after the back button was pressed.

**[Notes]:**

* The issue is not reproducible if the branch is changed from the Reference branch dropdown.

* Attaching a screen recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-6460)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/114369">Screen Recording 2026-02-11 at 4.38.11 PM.mov</a>

### PR DESCRIPTION
**Pull request by moibra05**
Because

- After making a selection from the filter dropdowns on the new results page and going back, the loading overlay would be stuck over the page content

This commit

- Fixes the indefinite page loading 

Fixes #14625

### CODE REVIEW

**Comment by moibra05** [comment]
https://github.com/user-attachments/assets/d49ba6a3-adb8-4c52-83cc-39f09bd8a713

File: experimenter/experimenter/nimbus_ui/static/js/index.js [hunk 1]
```diff
@@ -81,13 +81,19 @@ const setupHTMXLoadingOverlay = () => {
...
     if (loadingOverlay) {
       loadingOverlay.style.opacity = "0";
       loadingOverlay.style.pointerEvents = "none";
     }
+  };
+
+  document.addEventListener("htmx:afterRequest", hideOverlay);
+
+  window.addEventListener("popstate", function () {
+    setTimeout(hideOverlay, 10);
```
Comment (jaredlockhart) [inline experimenter/experimenter/nimbus_ui/static/js/index.js:96]: Aha ya that'd do it 👍

Comment (jaredlockhart) [reply experimenter/experimenter/nimbus_ui/static/js/index.js:96]: 10's a bit tight, if we find it doesn't work on prod maybe bump that up to 100.

Comment (moibra05) [reply experimenter/experimenter/nimbus_ui/static/js/index.js:96]: strangely enough it was working consistently with 0 but yea it likely won't be the same on prod
