### PR TITLE
fixes #5834 fix(nimbus): Fix review url

### LINKED ISSUE #5834: Fix remote settings review URL
Right now there is a double slash situation going on and a button that should be an external link

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1445)

### PR DESCRIPTION
**Pull request by k88hudson**
Because

* The reviewUrl is wrong for "Open Remote Settings"

This commit

* Changes the FormRemoteSettingsPending to be an anchor
* Removes a the leading slash on the remote settings URL

### CODE REVIEW

**Comment by LZoog** [comment]
This is going to cause conflicts with #5821 btw👀

**Comment by jodyheavener** [comment]
@k88hudson a rebase should help that failure

File: app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/mocks.tsx [hunk 1]
```diff
@@ -36,7 +35,8 @@ export const BaseSubject = ({
       timeoutEvent,
       rejectChange,
       approveChange,
-      startRemoteSettingsApproval,
+      reviewUrl:
+        "http://localhost:8888/v1/admin/#/buckets/main-workspace/collections/nimbus-mobile-experiments/records",
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/mocks.tsx:39]: Nit: could try and use [`REVIEW_URL`](https://github.com/mozilla/experimenter/pull/5835/files#diff-430239984ea0d023eca01d487e1e14285726983f13689b031f324e529d398c27R17) here

File: app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/FormRemoteSettingsPending.tsx [hunk 2]
```diff
@@ -26,19 +26,18 @@ const FormApproveConfirm = ({
 
         <div className="d-flex bd-highlight">
           <div>
-            <Button
+            <LinkExternal
               data-testid="open-remote-settings"
-              className="mr-2 btn btn-primary"
-              disabled={isLoading}
-              onClick={onConfirm}
+              className={`mr-2 btn btn-primary${isLoading ? " disabled" : ""}`}
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/FormRemoteSettingsPending.tsx:31]: This is clever in that the `disabled` class applies `pointer-events: none` to the button so it is not clickable. What it doesn't do is prevent focusing and triggering via the keyboard. Disabling links is [tricky](https://css-tricks.com/how-to-disable-links/). We _could_ remove the href as well, but even that doesn't do the whole trick. This is probably fine as-is.

File: app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.stories.tsx [hunk 3]
```diff
@@ -136,7 +134,8 @@ export const FormRemoteSettingsPendingStory = () => (
   <FormRemoteSettingsPending
     {...{
       isLoading: false,
-      onConfirm: action("confirm"),
+      reviewUrl:
+        "https://settings-writer.prod.mozaws.net/v1/admin/#/buckets/main-workspace/collections/nimbus-mobile-experiments/records",
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.stories.tsx:138]: Is this story intended to use a prod URL? Should it also use [`REVIEW_URL`](https://github.com/mozilla/experimenter/pull/5835/files#diff-430239984ea0d023eca01d487e1e14285726983f13689b031f324e529d398c27R17)?

File: app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.test.tsx [hunk 4]
```diff
@@ -14,17 +14,20 @@ import {
...
 } from "./mocks";
 
+const REVIEW_URL =
+  "http://localhost:8888/v1/admin/#/buckets/main-workspace/collections/nimbus-mobile-experiments/records";
+
 const Subject = ({
   rejectChange = () => {},
   approveChange = () => {},
-  startRemoteSettingsApproval = () => {},
+  reviewUrl = REVIEW_URL,
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.test.tsx:23]: I don't see any tests modifying this prop, so it could probably be removed and REVIEW_URL passed directly into the component.

File: app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.test.tsx [hunk 5]
```diff
@@ -58,7 +59,7 @@ describe("ChangeApprovalOperations", () => {
       "open-remote-settings",
     );
     fireEvent.click(openRemoteSettingsButton);
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/index.test.tsx:61]: I don't think this fireEvent is useful anymore and could probably be removed as you've done elsewhere

**Review by jodyheavener — COMMENTED** [review]
Works great for me, and as we discussed I can't see any reason this should stay a button over an anchor. Couple nits in tests/stories and I think we should be good.

File: app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/FormRemoteSettingsPending.tsx (hunk 2 above)
Comment (k88hudson) [reply app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/FormRemoteSettingsPending.tsx:31]: yeah, personally I don't think maintaining custom code for that is worth it for our use case

Comment (LZoog) [reply app/experimenter/nimbus-ui/src/components/ChangeApprovalOperations/FormRemoteSettingsPending.tsx:31]: We could use `classNames` here, something like `className={classNames("mr-2 btn btn-primary", isLoading && "disabled"))`

**Review by jodyheavener — APPROVED** [review]
LGTM after that prettier failure is fixed

**Comment by jaredlockhart** [comment]
>  why is vscode not helping me find these 

@k88hudson you might have to `yarn install` on your host environment to get the latest version, dependabot updates will automatically apply inside the container but not outside, so you can wind up with different version inside and outside the container with conflicting/inconsistent rules.
