### PR TITLE
Fix #4807 - fix(visualization) Add weekly significance computation.

### LINKED ISSUE #4807: Add weekly significance computation
Right now, significance is only computed as an "overall" result. There should also be weekly significance

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1070)
┆Issue Number: EXP-1070

### PR DESCRIPTION
**Pull request by emtwo**
Because:
* Significance was only computed overall and incorrectly shown for weekly results too

This commit:
* Computes weekly significance to show for weekly results

### CODE REVIEW

**Review by jaredlockhart — APPROVED** [review]
Looks good 👍

File: app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx [hunk 1]
```diff
@@ -217,14 +219,14 @@ const TableVisualizationRow: React.FC<{
...
     const metricDataList = metricData[branchComparison]["all"];
-    const significance = metricData["significance"];
 
     userCountsList.sort(formattedAnalysisPointComparator);
     metricDataList.sort(formattedAnalysisPointComparator);
 
     metricDataList.forEach((dataPoint: FormattedAnalysisPoint, i: number) => {
       const { lower, upper, point, count } = dataPoint;
       const userCountMetric = userCountsList[i]["point"];
+      const significance = metricData["significance"]?.[window][i + 1];
```
Comment (LZoog) [inline app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx:229]: Should we update any Storybook states in `TableVisualizationRow` to show what `overall` vs `weekly` looks like?

**Review by LZoog — APPROVED** [review]
LGTM, just one question about Storybook!

File: app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx (hunk 1 above)
Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx:229]: the items in `TableVisualizationRow` don't look different if it's `weekly` vs. `overall`. But the difference can be seen in the storybook of `TableResultsWeekly`
