### PR TITLE
fixes #3362 fix(visualization): Add start date, end date, and duration to results page.

### LINKED ISSUE #3362: Add start date, end date and duration to visualizations
This may need to be shown in the experiment overview / edit page, depending on if they are different.

But it definitely needs to be added to the visualization page as well.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-241)
┆Issue Number: EXP-241

### PR DESCRIPTION
**Pull request by emtwo**
Because:
* Users need to see dates and duration when looking at results

This commit:
* Makes them visible in the header whenever analysis is displayed

I thought this change was simple enough that it didn't seem necessary to create a separate `AppLayoutWithAnalysis` component.

### CODE REVIEW

File: app/experimenter/nimbus-ui/src/lib/visualization/utils.tsx [hunk 1]
```diff
@@ -27,3 +27,20 @@ export const getTableDisplayType = (
 
   return displayType;
 };
+
+export const humanDate = (date: string | number): string => {
```
Comment (k88hudson) [inline app/experimenter/nimbus-ui/src/lib/visualization/utils.tsx:31]: heh, i did the same thing here https://github.com/mozilla/experimenter/pull/4215/files#diff-38365926cca23693f8cf3838da07364cd7392d7ca2b1146dbdaa69e6e9af5a9fR9-R14

File: app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx [hunk 2]
```diff
@@ -7,31 +7,62 @@ import React from "react";
...
+            <span className="font-weight-bold"> {humanDate(endDate!)} </span>(
+            {stringDateSubtract(endDate!, startDate!)} days)
+          </div>
+        ) : (
+          ""
+        )}
+      </div>
+    </header>
+  );
+};
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx:65]: An alternative layout might be to instead wrap the status container in the row/col setup so the dates are fixed to the bottom of the header:

Screen Shot 2020-12-16 at 12 00 20 PM

A benefit of this would be that the header title and slug are variable in length and could expand as much as needed, whereas the status badges never vary width. It also helps maintain the title hierarchy.

Purely optional 😸

**Review by jodyheavener — COMMENTED** [review]
I apologize, I feel like I went a little overboard with that one section 😅 feel free to push back on anything lol

File: app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx [hunk 3]
```diff
@@ -7,31 +7,62 @@ import React from "react";
...
+            <StatusPill label="Review" active={status.review} />
+            <StatusPill label="Live" active={status.live} />
+            <StatusPill
+              label="Complete"
+              active={status.complete}
+              padded={false}
+            />
+          </p>
+        </div>
+        {analysisRequired ? (
```
[the remark this answers is not in the document]
Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx]: yep. Or `status.complete`. Updated this

File: app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx (hunk 2 above)
Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx]: I'm not sure I follow what you mean by "wrap the status container in the row/col setup". Could you show it roughly in jsx? Thanks! =)

**Comment by emtwo** [comment]
@jodyheavener finally got around to this and it's ready for another look! :)

File: app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx (hunk 2 above)
Comment (jodyheavener) [reply app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx]: @emtwo sure! Here's what I meant: https://gist.github.com/jodyheavener/bc57dbfd0f0bb66235ffc27c945865e7

Comment (jodyheavener) [reply app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx]: Also FYI I am working on a issue that updates the `humanDate` utility to only show the year if it's not the current year.

Comment (emtwo) [reply app/experimenter/nimbus-ui/src/components/HeaderExperiment/index.tsx]: Thanks!

**Review by jodyheavener — APPROVED** [review]
Wooo
