### PR TITLE
fix(tests): Update filter expression script to use ExperimentAPI module.

### LINKED ISSUE #12851: Targeting Integration Tests are failing on CI
Looks like we have a JS error where it seems a function has changed/been removed upstream:

```
 selenium.common.exceptions.JavascriptException: Message: TypeError: ExperimentManager.ExperimentManager.createTargetingContext is not a function
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-5568)

### PR DESCRIPTION
**Pull request by b4handjr**
Because

- Our targeting tests are failing due to a change in an upstream module we consume to creating targeting contexts.

This commit

- Updates our script to use the newer `ExperimenterAPI` module.

Fixes #12851

### CODE REVIEW

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 1]
```diff
@@ -37,7 +38,7 @@ async function remoteSettings(arguments) {
             isDefaultHandler: {},
             defaultPDFHandler: {}
         }, // Workaround for supporting background tasks
-        ExperimentManager.ExperimentManager.createTargetingContext(),
+        ExperimentAPI._manager.createTargetingContext(),
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js:21]: `_manager` is deprecated as of Firefox 140 https://searchfox.org/mozilla-release/source/toolkit/components/nimbus/ExperimentAPI.sys.mjs#278 (and apparently this comment has a typo whoops)

```suggestion
        ExperimentAPI.manager.createTargetingContext(),
```

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 2]
```diff
@@ -23,10 +23,11 @@ async function remoteSettings(arguments) {
             throw ex;
         }
     }
-    const ExperimentManager = ChromeUtils.importESModule("resource://nimbus/lib/ExperimentManager.sys.mjs");
+    const { ExperimentAPI } = ChromeUtils.importESModule("resource://nimbus/ExperimentAPI.sys.mjs");
     const TargetingContext = ChromeUtils.importESModule("resource://messaging-system/targeting/Targeting.sys.mjs");
 
     const _experiment = JSON.parse(arguments[1]);
+    ExperimentAPI.ready();
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]: This returns a promise
```suggestion
    await ExperimentAPI.ready();
```

**Comment by freshstrangemusic** [comment]
There is a typo in the PR title: `ExperimetAPI`

File: experimenter/tests/integration/nimbus/utils/filter_expression.js (hunk 1 above)
Comment (freshstrangemusic) [reply experimenter/tests/integration/nimbus/utils/filter_expression.js:21]: We're stuck in 139 for now :)

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 3]
```diff
@@ -1,55 +1,64 @@
...
-    return result;
 }
 
-let results = remoteSettings(arguments);
+// Get the Selenium callback
+const [targetingString, recipe] = arguments;
+const callback = arguments[arguments.length - 1];
 
-return results;
+remoteSettings(targetingString, recipe, callback);
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]: Instead of taking the callback as an arg, lets do `remoteSettings(targetingString, recipe).then(callback, () => null)`

It makes the control flow of `remoteSettings` cleaner and it doesnt need a bunch of try/catch.

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 4]
```diff
@@ -1,55 +1,64 @@
...
+                defaultPDFHandler: {}
+            },
+            ExperimentAPI._manager.createTargetingContext(),
+            ASRouterTargeting.ASRouterTargeting.Environment
+        );
+
+        const targetingContext = new TargetingContext.TargetingContext(context);
+        let result = false;
+        try {
+            result = await targetingContext.evalWithDefault(targetingString) !== undefined;
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]: if we dont take callback as an arg, we can just return immediately here. We dont even need to try/catch

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 5]
```diff
@@ -1,55 +1,64 @@
...
+        } catch (err) {
+            result = null;
+        }
+
+        callback(result);
     } catch (err) {
-        result = null;
+        callback(null);
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]: and here.

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 6]
```diff
@@ -1,55 +1,64 @@
...
     }
-    return result;
 }
 
-let results = remoteSettings(arguments);
+// Get the Selenium callback
+const [targetingString, recipe] = arguments;
+const callback = arguments[arguments.length - 1];
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]:
```suggestion
const [targetingString, recipe, callback] = arguments;
```

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 7]
```diff
@@ -1,55 +1,64 @@
...
+        let ASRouterTargeting;
+        try {
+            ASRouterTargeting = ChromeUtils.importESModule("resource:///modules/asrouter/ASRouterTargeting.sys.mjs");
+        } catch (ex) {
+            if (ex.result === Cr.NS_ERROR_FILE_NOT_FOUND) {
+                ASRouterTargeting = ChromeUtils.importESModule("resource://activity-stream/lib/ASRouterTargeting.sys.mjs");
+            } else {
+                throw ex;
+            }
         }
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]: We're on 139+ so we can drop the try/catch and import from modules/asrouter directly.

Doesn't have to be in this change tho.

**Review by freshstrangemusic — CHANGES_REQUESTED** [review]

File: experimenter/tests/integration/nimbus/pages/browser/__init__.py [hunk 8]
```diff
@@ -8,12 +8,12 @@
...
 class Browser:
-    def execute_script(self, *args, script=None, context=None):
+    def execute_async_script(self, *args, script=None, context=None):
         if "chrome" in context:
             with self.context(self.CONTEXT_CHROME):
-                return self.execute_script(script, *args)
+                return self.execute_async_script(script, *args)
         else:
-            return self.execute_script
+            return self.execute_async_script
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/pages/browser/__init__.py]: I do not understand how this is supposed to work

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 9]
```diff
@@ -1,55 +1,48 @@
...
-
+async function remoteSettings(targetingString, recipe) {
     /*
-        Arguments contains 2 items.
-        arguments[0] - the JEXL targeting string
-        arguments[1] - the experiment recipe
+    Arguments contains 2 items.
+    arguments[0] - the JEXL targeting string
+    arguments[1] - the experiment recipe
     */
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]: nit i would put this above the arguments destructuring at the end of the file. Also update for the callback param

File: experimenter/tests/integration/nimbus/utils/filter_expression.js [hunk 10]
```diff
@@ -1,55 +1,48 @@
...
     } catch (err) {
-        result = null;
+        return null;
     }
-    return result;
 }
 
-let results = remoteSettings(arguments);
+const [targetingString, recipe] = arguments;
+const callback = arguments[arguments.length - 1]
```
Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/utils/filter_expression.js]:
```suggestion
const [targetingString, recipe, callback] = arguments;
```

File: experimenter/tests/integration/nimbus/pages/browser/__init__.py (hunk 8 above)
Comment (b4handjr) [reply experimenter/tests/integration/nimbus/pages/browser/__init__.py]: We use it in the test
```
with filter_expression_path.open() as js:
        result = Browser.execute_async_script(
            selenium,
            targeting,
            json.dumps({"experiment": recipe}),
            script=js.read(),
            context="chrome",
        )
```

Comment (freshstrangemusic) [reply experimenter/tests/integration/nimbus/pages/browser/__init__.py]: In the example you gave, context="chrome" so we're in the other branch. From inspection, you would have to use this like:

```
result = Browser.execute_async_script()(script)
```

Comment (freshstrangemusic) [inline experimenter/tests/integration/nimbus/pages/browser/__init__.py]: This should be

```
return self.execute_async_script(script, *args)
```

see my other comment.

**Review by freshstrangemusic — APPROVED** [review]
