### PR TITLE
fixes #5750 fix(nimbus): made branch tables fixed 

### LINKED ISSUE #5750: Branch tables with uninterrupted strings in the feature configuration forces the /nimbus/ page to display a horizontal scrollbar
**[Steps to reproduce]:**

1. Navigate to [this experiment ticket](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cmuresan-nimbus-smoke-05272021).
1. Scroll down to the bottom of the page.
1. Observe the "treatment" branch.

**[Expected result]:**

* The "treatment" table has a horizontal scrollbar inside the cell the value is in.

**[Actual result]:**

* The whole page has a horizontal scrollbar and the table's boundaries are extended to display the full uninterrupted string.

**[Notes]:**

* The issue is also reproducible on the /request-review page.
* Attached is a screen recording of the issue.
* [PI-1051]

branches tables with uninterrupted strings in their feature configuration do not have a horizontal scrollbar in their respective cell

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1355)

### PR DESCRIPTION
**Pull request by anthonytran7757**
Because

* branch tables with uninterrupted strings forces the nimbus page to display a horizontal scrollbar

This commit

* fixes the branch table to have a horizontal scrollbar for long strings inside the cell

### CODE REVIEW

**Comment by anthonytran7757** [comment]
I have included a screenshot of the fixed branch table 
branch table fix

**Comment by anthonytran7757** [comment]
need to fix column alignment issue

**Comment by anthonytran7757** [comment]
I have included a screenshot of the the fixed table cell alignment issue
branch table fix

File: app/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.tsx [hunk 1]
```diff
@@ -69,7 +69,16 @@ const TableBranch = ({
...
+    <Table
+      bordered
+      data-testid="table-branch"
+      className="mb-4 table-fixed"
+      id={slug}
+    >
+      <colgroup>
+        <col className="w-33" />
+        <col />
+      </colgroup>
```
Comment (jodyheavener) [inline app/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.tsx:81]: Hey @anthonytran7757 can you elaborate on what this empty colgroup is doing? Is this a hacky way of fixing the problem, or could there be a better way?

**Review by jodyheavener — CHANGES_REQUESTED** [review]
While I'm here - can I get you to squash and format your commit messages according to our [Git Commit Guidelines](https://github.com/mozilla/experimenter/blob/main/contributing.md#git-commit-guidelines)?

File: app/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.tsx (hunk 1 above)
Comment (anthonytran7757) [reply app/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.tsx:81]: Hey @jodyheavener I've tried some other things, but this was the only one that worked for me aside from setting a colSpan={1} or colSpan={2} for each of the cells to maintain the 33% to 66% ratio between the columns. Could I get some guidance to find a less hacky solution?

Comment (jodyheavener) [reply app/experimenter/nimbus-ui/src/components/Summary/TableBranches/index.tsx:81]: @anthonytran7757 I did some more research into this and found it to be an OK approach, and also couldn't find a better way of doing this without removing the thead. If you want to squash and reword your commit messages I can merge 👍

**Review by jodyheavener — APPROVED** [review]
Thanks @anthonytran7757
